#!/bin/bash
#SBATCH --nodes=1
#SBATCH --cpus-per-task=24
#SBATCH --job-name="patus"
#SBATCH --time=00:01:00
#SBATCH --time-min=00:00:10
#SBATCH --output=${RESULTFILE}
#SBATCH --error=${RESULTFILE}.err
#==================== START ====================
export OMP_NUM_THREADS=${NUMTHREADS}
export KMP_AFFINITY=compact,verbose
${EXECUTABLE} ${PARAMS}
exit
#====================  END  ====================
